version: '3.8'

services:
  web-prod:
    build:
      context: ./prod-fetch/VideGrenierEnLigne
      dockerfile: ../../Dockerfile
    container_name: web_prod
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./prod-fetch/VideGrenierEnLigne:/var/www
      - ./prod-fetch/VideGrenierEnLigne/public:/var/www/html
    depends_on:
      - db-prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 10s
    networks:
      - videgrenier-prod
    environment:
      - SECRET_KEY=secret_key
      - DB_HOST=db-prod
      - DB_NAME=videgrenierenligne
      - DB_USER=root
      - DB_PASSWORD=root_pwd

  db-prod:
    image: mariadb:10.9
    container_name: db_prod
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=videgrenierenligne
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp_pwd
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql
      - ./prod-fetch/VideGrenierEnLigne/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - videgrenier-prod

volumes:
  db_data:

networks:
  videgrenier-prod:
